// <auto-generated />
namespace Sigma.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TableAdded1223 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableAdded1223));
        
        string IMigrationMetadata.Id
        {
            get { return "201608111035155_TableAdded1223"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
